[package]
name = "pluginator"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "Utilities for easier creation of plugins in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7.4"
